"""create click_logs table

Revision ID: b3ffefc7896e
Revises: 3441f80f7a73
Create Date: 2025-04-05 20:19:02.476136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ffefc7896e'
down_revision: Union[str, None] = '3441f80f7a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('click_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_click_logs_id'), 'click_logs', ['id'], unique=False)
    op.create_index(op.f('ix_click_logs_short_code'), 'click_logs', ['short_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_click_logs_short_code'), table_name='click_logs')
    op.drop_index(op.f('ix_click_logs_id'), table_name='click_logs')
    op.drop_table('click_logs')
    # ### end Alembic commands ###
